language: cpp
jobs:
  include:
    - stage: "Building"
    
      name: "Check"
      os: linux
      compiler: gcc
      script:
        - wc -l lb1.cpp
        - gcc -c lb1.cpp -o 111.txt
        
        
    - stage: Documentation
    
      name: "Doxygen"
      os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install doxygen
      script:
        - git clone https://github.com/warfka/firstRep.io.git
        - cd firstRep.io
        - rm -rf ru
        - doxygen
        - git config --global user.name "warfka"
        - git config --global user.email "travis@travis.org"
        - git add -A
        - git commit -am "Update doc from Travis CI"
        - git config --global push.default simple
        - git push -f -q https://warfka:$GITHUB_API_KEY@github.com/warfka/firstRep.io.git
