before_instal: sudo apt-get install doxygen
language: cpp 
jobs:
  include:
     - stage: test
     compiler: cpp
     script:
     - wc -l 1lb.cpp
   
     compiler: gсс
      script:
     - wc -l 1fghnb.cpp
   

branches:
  only:
    - master
